try {
    const m = 1;
    const n = m + z;
} catch (err) {
    // console.log("error", err);
    console.log('error content catch content')
}